In [ ]:
import numpy as np
input1 = np.array([[0,0,0,0],
          [1,1,1,1],
          [1,0,0,1],
          [1,1,1,1]])
input2 = np.array([[1,1,1,0],
          [1,0,1,0],
          [1,1,1,0],
          [0,0,0,1]])
input3 = np.array([[0,0,0,0],
          [0,1,1,1],
          [0,0,1,0],
          [0,0,0,0]])
input4 = np.array([[0,0,0,1],
          [0,1,0,0],
          [1,1,1,1],
          [0,1,0,0]])
filter1 = np.array([[0,1,0],
           [1,1,1],
           [0,1,0]])
filter2 = np.array([[1,1,1],
           [1,0,1],
           [1,1,1]])
bias = -2

In [ ]:
output_height = input1.shape[0] - filter.shape[0] + 1
output_width =  input1.shape[1] - filter.shape[1] + 1
def Stride1(inputx, filter):
    output = np.zeros((output_height,output_width))
    for i in range(output_height):
      for j in range(output_width):
        for ii in range(filter.shape[0]):
          for jj in range(filter.shape[1]):
            output[i,j] += inputx[i+ii,j+jj] * filter[ii,jj]
        output[i,j] += bias
    return output


In [ ]:
def show_stride1():
  for i, n in enumerate([input1, input2, input3, input4]):
    for j, m in enumerate([filter1, filter2]):
       print(f'Stride1 of input{i +1}, filter{j +1} is: \n', Stride1(n,m))


In [ ]:
show_stride1()

Stride1 of input1, filter1 is: 
 [[1. 1.]
 [1. 1.]]
Stride1 of input1, filter2 is: 
 [[1. 1.]
 [5. 5.]]
Stride1 of input2, filter1 is: 
 [[2. 1.]
 [1. 1.]]
Stride1 of input2, filter2 is: 
 [[6. 2.]
 [2. 1.]]
Stride1 of input3, filter1 is: 
 [[0. 2.]
 [0. 0.]]
Stride1 of input3, filter2 is: 
 [[0. 1.]
 [1. 1.]]
Stride1 of input4, filter1 is: 
 [[0. 0.]
 [3. 1.]]
Stride1 of input4, filter2 is: 
 [[1. 3.]
 [2. 2.]]


In [ ]:
def MaxPooling(inputx):
    output = np.zeros((output_height,output_width))
    for m,i in enumerate(range(0,inputx.shape[0],2)):
      for n,j in enumerate(range(0,inputx.shape[1],2)):
        temp = []
        for ii in range(output_width):
          for jj in range(output_width):
            temp.append(inputx[i+ii,j+jj])
        output[m,n] = max(temp)
    return output

In [ ]:
def show_MaxPooling():
  for i, n in enumerate([input1, input2, input3, input4]):
    print(f'MaxPooling of input{i +1} is: \n', MaxPooling(n))


In [ ]:
show_MaxPooling()

MaxPooling of input1 is: 
 [[1. 1.]
 [1. 1.]]
MaxPooling of input2 is: 
 [[1. 1.]
 [1. 1.]]
MaxPooling of input3 is: 
 [[1. 1.]
 [0. 1.]]
MaxPooling of input4 is: 
 [[1. 1.]
 [1. 1.]]
